---
- name: Create ticket with notes
  hosts: localhost
  gather_facts: no
  connection: local
  collections:
  - servicenow.servicenow

  tasks:
  - name: include vars
    include_vars: change_request_vars.yml

  #creates a new change request assigned to the change management group. 
  - name: Create a change request
    snow_record:
      state: present
      table: change_request
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      data:
        severity: "{{ sn_severity }}"
        priority: "{{ sn_priority }}"
        short_description: "This is a test opened by Bob via Ansible"
        assignment_group: a715cd759f2002002920bde8132e7018
    register: new_incident

  - debug: 
      var: new_incident.record