---
- name: Create ticket with notes
  hosts: localhost
  gather_facts: no
  connection: local
  collections:
  - servicenow.servicenow

  tasks:
  - name: include vars
    include_vars: change_request_vars.yml

  - name: updates change request to assess state
    snow_record:
      state: present
      table: change_request
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      number: CHG0030011
      data:
        # the -4 means the change request will move to assess
        state: -4
        work_notes: "working on a dream"
    register: new_incident

  - debug: 
      var: incident.record.state